version: '3.4'

services:

  eticaretdb:
    container_name: eticaretdb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
        - "27017:27017" 
  eticaret.products:
    container_name: products
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://eticaretdb:27017"
    depends_on:
        - eticaretdb
    
    ports:
      - "8000:80"
    volumes:
     - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
     - ${HOME}/ASP.NET/Https:/root/.aspnet/https

  eticaret.categories:
    container_name: categories
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CategoryDatabaseSettings:ConnectionString=mongodb://eticaretdb:27017"
    depends_on:
        - eticaretdb
    ports:
      - "8001:80"
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https
